version: 0.0
os: linux
files:
  - source: /
    destination: /opt/Node-JS-Demo-Project 
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ubuntu

