version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - npm install
      - npm run build  # If you have build commands, otherwise skip.
artifacts:
  files:
    - '**/*'
  base-directory: artifacts

